"""PortAudio bindings for Python."""

from .portaudio_ext import (  # ty: ignore[unresolved-import]
    # 高レベル API
    SampleFormat,
    list_devices,
    list_input_devices,
    list_output_devices,
    open_input,
    open_output,
    # クラス
    DeviceInfo,
    Stream,
    StreamParameters,
    # 低レベル API - 定数
    CLIP_OFF,
    CUSTOM_FORMAT,
    DITHER_OFF,
    FLOAT32,
    FRAMES_PER_BUFFER_UNSPECIFIED,
    INPUT_OVERFLOW,
    INPUT_UNDERFLOW,
    INT8,
    INT16,
    INT24,
    INT32,
    NEVER_DROP_INPUT,
    NO_DEVICE,
    NO_FLAG,
    NON_INTERLEAVED,
    OUTPUT_OVERFLOW,
    OUTPUT_UNDERFLOW,
    PRIME_OUTPUT_BUFFERS_USING_STREAM_CALLBACK,
    PRIMING_OUTPUT,
    UINT8,
    # 低レベル API - Enum
    ErrorCode,
    HostApiTypeId,
    StreamCallbackResult,
    # 低レベル API - 構造体
    HostApiInfo,
    HostErrorInfo,
    StreamCallbackTimeInfo,
    StreamInfo,
    VersionInfo,
    # 低レベル API - 関数
    get_all_devices,
    get_all_host_apis,
    get_default_host_api,
    get_default_input_device,
    get_default_output_device,
    get_device_count,
    get_device_info,
    get_error_text,
    get_host_api_count,
    get_host_api_info,
    get_input_devices,
    get_last_host_error_info,
    get_output_devices,
    get_sample_size,
    get_version,
    get_version_info,
    get_version_text,
    host_api_device_index_to_device_index,
    host_api_type_id_to_host_api_index,
    is_format_supported,
    sleep,
)

__all__ = [
    # 高レベル API
    "SampleFormat",
    "list_devices",
    "list_input_devices",
    "list_output_devices",
    "open_input",
    "open_output",
    # クラス
    "DeviceInfo",
    "Stream",
    "StreamParameters",
    # 低レベル API - 定数
    "FLOAT32",
    "INT32",
    "INT24",
    "INT16",
    "INT8",
    "UINT8",
    "CUSTOM_FORMAT",
    "NON_INTERLEAVED",
    "NO_FLAG",
    "CLIP_OFF",
    "DITHER_OFF",
    "NEVER_DROP_INPUT",
    "PRIME_OUTPUT_BUFFERS_USING_STREAM_CALLBACK",
    "INPUT_UNDERFLOW",
    "INPUT_OVERFLOW",
    "OUTPUT_UNDERFLOW",
    "OUTPUT_OVERFLOW",
    "PRIMING_OUTPUT",
    "NO_DEVICE",
    "FRAMES_PER_BUFFER_UNSPECIFIED",
    # 低レベル API - Enum
    "ErrorCode",
    "HostApiTypeId",
    "StreamCallbackResult",
    # 低レベル API - 構造体
    "VersionInfo",
    "HostApiInfo",
    "StreamInfo",
    "HostErrorInfo",
    "StreamCallbackTimeInfo",
    # 低レベル API - 関数
    "get_version",
    "get_version_text",
    "get_version_info",
    "get_error_text",
    "get_last_host_error_info",
    "get_host_api_count",
    "get_default_host_api",
    "get_host_api_info",
    "host_api_type_id_to_host_api_index",
    "host_api_device_index_to_device_index",
    "get_all_host_apis",
    "get_device_count",
    "get_default_input_device",
    "get_default_output_device",
    "get_device_info",
    "get_all_devices",
    "get_input_devices",
    "get_output_devices",
    "is_format_supported",
    "get_sample_size",
    "sleep",
]
